export const GET_REGIONS_AND_SIZES = 'GET_REGIONS_AND_SIZES'
export const SIZES_AND_REGIONS_LOADING = 'SIZES_AND_REGIONS_LOADING'
export const CREATE_SERVER_LOADING = 'CREATE_SERVER_LOADING'
export const CREATE_SERVER = 'CREATE_SERVER'
